edit()
startEdit()
cd('/WLDFSystemResources/Module-FMWDFW/WLDFResource/Module-FMWDFW/WatchNotification/Module-FMWDFW')
cmo.setEnabled(false)
cmo.setLogWatchSeverity('Error')
cmo.setSeverity('Error')
save()
activate()
